[workspace]
# Automatically update all workspace dependencies
allow_dirty = false
git_release_enable = false
publish = false
semver_check = true

[[package]]
name = "plato"
changelog_include = ["core"]
changelog_path = "CHANGELOG.md"
changelog_update = true
git_release_enable = true
publish = false

# Changelog configuration
[changelog]
# Changelog header
header = "# Changelog\n\nAll notable changes to this project will be documented in this file.\n\nThe format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),\nand this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n"
# Group commits by type
commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->Features" },
  { message = "^fix", group = "<!-- 1 -->Bug Fixes" },
  { message = "^perf", group = "<!-- 2 -->Performance" },
  { message = "^refactor", group = "<!-- 3 -->Refactoring" },
  { message = "^doc", group = "<!-- 4 -->Documentation" },
  { message = "^style", group = "<!-- 5 -->Styling" },
  { message = "^test", group = "<!-- 6 -->Testing" },
  { message = "^build", group = "<!-- 7 -->Build" },
  { message = "^ci", group = "<!-- 8 -->CI" },
  { message = "^chore", group = "<!-- 9 -->Miscellaneous" },
]
