[package]
name = "importer"
version = "0.9.46"
edition = "2021"
authors = ["Cadmus Authors", "Bastien Dejean <nihilhill@gmail.com> (original Plato author)"]

[[bin]]
name = "cadmus-import"
path = "src/main.rs"

[dependencies]
cadmus-core = { path = "../core" }
getopts = "0.2.24"
