[package]
name = "cadmus"
version = "0.9.45"
edition = "2021"
authors = ["Cadmus Authors", "Bastien Dejean <nihilhill@gmail.com> (original Plato author)"]

[[bin]]
name = "cadmus"
path = "src/main.rs"

[features]
test = ["cadmus-core/test"]

[dependencies]
cadmus-core = { path = "../core" }
